spring.application.name=real-time-messaging-platform


spring.datasource.url=jdbc:postgresql://dpg-d79r0eudqaus73dkb1sg-a.frankfurt-postgres.render.com:5432/real_time_messaging_platform_db
spring.datasource.username=real_time_messaging_platform_db_user
spring.datasource.password=GYEBoF1wglK6BFKufZcxS3jRUxEwNY6L

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.validation-timeout=5000

server.port=8080
server.error.include-message=always

app.jwt.secret=your_super_secret_key_that_is_long_enough_for_jwt_security_123456789
app.jwt.expiration-ms=86400000
app.cors.allowed-origin=${APP_CORS_ALLOWED_ORIGIN:http://localhost:5173}
